config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("empresa.urls")),
    path('usuario', include("usuario.urls")),
    path('sede', include("sede.urls")),
    path('turno', include("turno.urls")),
    path('accounts/', include("autenticacion.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.urls import path
from .views import index , EmpresaCreateView , EmpresaListView , EmpresaUpdateView, EmpresaDeleteView, invitarUsuario , load_estado, load_ciudad

urlpatterns = [
    path('', index , name='index'),
    path('empresa/crear/', EmpresaCreateView.as_view() , name='empresa_crear'),
    path('empresa/listar/', EmpresaListView.as_view() , name='empresa_listar'),
    path('empresa/actualizar/<int:pk>', EmpresaUpdateView.as_view(), name='empresa_actualizar'),
    path('empresa/eliminar/<int:pk>', EmpresaDeleteView.as_view(), name='empresa_eliminar'),
    path('empresa/invitar_usurio/', invitarUsuario , name='invitar_usurio'),
    path('ajax/load-estado/', load_estado , name='ajax_load_estado'),
    path('ajax/load-ciudad/', load_ciudad , name='ajax_load_ciudad'),


]

sede/urls.py
from django.urls import path
from .views import SedeCreateView, SedeListView, SedeUpdateView, SedeaDeleteView

urlpatterns = [
    path('sede/crear/', SedeCreateView.as_view() , name='sede_crear'),
    path('sede/listar/', SedeListView.as_view() , name='sede_listar'),
    path('sede/actualizar/<int:pk>', SedeUpdateView.as_view(), name='sede_actualizar'),
    path('sede/eliminar/<int:pk>', SedeaDeleteView.as_view(), name='sede_eliminar'),



]

empresa/models.py
from django.db import models
from pais.models import Pais
from pais.models import Estado
from pais.models import Ciudad
from usuario.models import Usuario

class Empresa(models.Model):
    usuario_super = models.ForeignKey(Usuario,on_delete=models.CASCADE, null=True, blank=True)
    nit = models.IntegerField(default=1)
    nom_empresa = models.CharField(max_length=300)
    nom_comercial = models.CharField(max_length=300)
    direccion = models.CharField(max_length=300)
    telefono = models.IntegerField(default=1)
    correo = models.EmailField(max_length=150)
    web = models.URLField(max_length=200)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, null=True, blank=True)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=True, blank=True)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='empresa/', blank=True)

    def __str__(self):
        return self.nom_empresa

empresa/forms.py
from django import forms
from .models import Empresa
from pais.models import Estado
from pais.models import Ciudad



class EmpresaForm(forms.ModelForm):
    class Meta:
        model = Empresa
        fields = ['nit', 'nom_empresa', 'nom_comercial', 'direccion', 'telefono', 'correo', 'web', 'pais', 'estado', 'ciudad', 'image']
        labels = {
            'nit': 'Nit',
            'nom_empresa': 'Nombre Empresa',
            'nom_comercial': 'Nombre Comercial',
            'direccion': 'Direccion',
            'telefono': 'Telefono',
            'correo': 'E-mail',
            'web': 'Sitio web',
            'pais': 'Pais',
            'estado': 'Estado',
            'ciudad': 'Ciudad',
            'imagen' : 'Foto'

        }

empresa/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Empresa
from django.urls import reverse_lazy
from .forms import EmpresaForm
from django.contrib.auth.decorators import login_required
from pais.models import Pais , Estado , Ciudad

from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.conf import settings

@login_required(login_url='/accounts/acceder')
def index(request):
    return render( request,'index.html')

def send_email(mail):
    #print(mail)
    context = { 'mail' : mail }
    template = get_template('correo.html')
    content = template.render(context)

    email = EmailMultiAlternatives(
        'Un correo de prueba',
        'Invitacion usuario a registrarse',
        settings.EMAIL_HOST_USER,
        [mail]
    )

    email.attach_alternative(content,'text/html')
    email.send()

def invitarUsuario(request):
    if request.method == 'POST':
        mail = request.POST.get('mail')
        send_email(mail)
    return render( request,'enviar_correo.html')


def load_estado(request):
    pais_id = request.GET.get('pais')
    estados = Estado.objects.filter(pais_id=pais_id).order_by('nombre')
    return render(request, 'estado_dropdown_list_options.html', {'estados': estados})

def load_ciudad(request):
    estado_id = request.GET.get('estado')
    ciudades = Ciudad.objects.filter(estado_id=estado_id).order_by('nombre')
    return render(request, 'ciudad_dropdown_list_options.html', {'ciudades': ciudades})

class EmpresaCreateView(CreateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = 'empresa/empresa_form.html'
    success_url = reverse_lazy('index')


class EmpresaListView(ListView):
    model = Empresa
    context_object_name = 'empresas'
    template_name = 'empresa/listar_empresa.html'
    queryset = Empresa.objects.all()
    paginate_by = 3


class EmpresaUpdateView(UpdateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = 'empresa/empresa_form.html';
    success_url = reverse_lazy('empresa_listar')


class EmpresaDeleteView(DeleteView):
    model = Empresa
    success_url = reverse_lazy('empresa_listar')

templates/empresa/empresa_confirm_delete.html
{% extends 'index.html' %}
{% block title %} Eliminar Empresa {% endblock %}

{% block content %}
<br>

<form action="" method="post" class="bt-2">

    {% csrf_token %}


    <div class="card">
        <div class="card-header bg-warning text-white">
          <h4>Alerta</h4>
        </div>
        <div class="card-body">
          <h3 class="card-text">Esta seguro de eliminar la empresa : {{ object }} de la aplicación ?</h3>
          <button class="btn btn-danger" type="submit" value="confirmacion">Confirmar</button>
          <a href="{% url 'empresa_listar'  %}" class="btn btn-secondary"> Regresar </a>
        </div>
      </div>


</form>
<br>
{% endblock %}

templates/empresa/empresa_form.html
{% extends 'index.html' %}
 
{% block content %}
{% load widget_tweaks %}
{% load static %}
  <h2>Person Form</h2>
 
  <form method="post" class="mt-2" id="empresaForm" data-estados-url="{% url 'ajax_load_estado' %}" data-ciudad-url="{% url 'ajax_load_ciudad' %}" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    <table>
      <!-- {{ form.as_table }} -->
    </table>


 {% for field in form.visible_fields %}
   <div class="form-group">
  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
  {{ field|add_class:'form-control' }}

  {% for error in field.errors %}
    <span class="help-block">{{ error }}</span>
  {% endfor %}
   </div>
 {% endfor %}
      <button type="submit" class="btn btn-success">Guardar</button>
  </form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <script>
    $("#id_pais").change(function () {
      var url = $("#empresaForm").attr("data-estados-url");
      var paisId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'pais': paisId
        },
        success: function (data) {
          $("#id_estado").html(data);
        }
      });

    });

    $("#id_estado").change(function () {
      var url = $("#empresaForm").attr("data-ciudad-url");
      var estadoId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'estado': estadoId
        },
        success: function (data) {
          $("#id_ciudad").html(data);
        }
      });

    });
  </script>
 
{% endblock %}

templates/empresa/listar_empresa.html
{% extends 'index.html' %}

{% block title %} Listar Empresa {% endblock %}

{% block content %}

    <H1>Empresas</H1>
<hr />
<div class="row">

    <div class="col-12 m-2">
        <div class="row">
            {% for empresa in empresas %}
                <div class="col-md-3 col-sm-12 col-lg-4 pb-3">
                    <div class="card">
                        {% if empresa.image %}
                        <img src="{{ empresa.image.url }}" height="300" class="card-img-top" alt="{{ empresa.nom_comercial }}" />
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ empresa.nom_comercial}}</h5>
                            <h5 class="card-title">{{ empresa.id }}</h5>
                            <h5 class="card-title">{{ empresa.sede.empresa_id }}</h5>
                        </div>
                        {% if empresa.id %}
                        <a href="{% url 'sede_listar' %}" class="btn btn-secondary"> Ingresar </a>
                        {% endif %}
                        <div class="card-footer text-center">

                        <hr />
                            <a href="{% url 'empresa_actualizar' empresa.id %}" class="btn btn-secondary"> editar </a>
                            <a href="{% url 'empresa_eliminar' empresa.id %}" class="btn btn-danger"> eliminar </a>


                        </div>
                    </div>
                </div>
            {% endfor %}

            {% include 'paginacion.html' %}

        </div>
    </div>
</div>



{% endblock %}